-- TOP Engineers Plus Data Enrichment Script
-- This script enriches the TOP Engineers Plus workspace with comprehensive company context
-- Workspace ID: 01K5D01YCQJ9TJ7CT4DZDE79T1

-- Update the workspace with TOP Engineers Plus context
UPDATE "workspaces" 
SET 
  "description" = 'TOP Engineers Plus - Communications Engineering firm specializing in critical infrastructure and broadband deployment. We simplify complex communication engineering challenges and deliver strategic clarity for thriving communities.',
  "businessModel" = 'Engineering Consulting',
  "serviceFocus" = ARRAY['Critical Infrastructure', 'Broadband Deployment', 'Communications Engineering', 'Utility Infrastructure'],
  "stakeholderApproach" = 'Client-Centric',
  "projectDeliveryStyle" = 'Strategic Clarity',
  "companyContext" = '{
    "mission": "Simplify complex communication engineering challenges and deliver strategic clarity",
    "vision": "Be the leading Communications Engineering firm for critical infrastructure and broadband deployment",
    "coreValues": ["Excellence", "Integrity", "Innovation", "Client-Centric Approach"],
    "marketPosition": "Competitive Communications Engineering Firm",
    "targetSegments": ["Utility Companies", "Municipalities", "Infrastructure Organizations"],
    "primaryServices": ["Technology Expertise", "Process Development", "Organizational Alignment", "Change Management"],
    "competitiveAdvantages": ["Complexity Simplified", "Comprehensive Expertise", "Strategic Clarity", "Proven Track Record"],
    "clientEngagementModel": "Client-Centric Approach",
    "communicationStyle": "Professional",
    "industrySpecialization": ["Communications Engineering", "Utility Infrastructure", "Critical Infrastructure", "Broadband Deployment"],
    "valueProposition": "Simplify, Optimize, Excel: The TOP Engineers Plus Advantage",
    "businessApproach": "Turn complex challenges into simple, actionable solutions for thriving communities"
  }'::jsonb,
  "updatedAt" = NOW()
WHERE "id" = '01K5D01YCQJ9TJ7CT4DZDE79T1';

-- Update or create TOP Engineers Plus company record with enriched context
INSERT INTO "companies" (
  "id",
  "workspaceId",
  "name",
  "legalName",
  "tradingName",
  "website",
  "email",
  "phone",
  "address",
  "city",
  "state",
  "country",
  "postalCode",
  "industry",
  "sector",
  "size",
  "description",
  "notes",
  "tags",
  "accountType",
  "tier",
  "vertical",
  "businessChallenges",
  "businessPriorities",
  "competitiveAdvantages",
  "growthOpportunities",
  "marketPosition",
  "strategicInitiatives",
  "successMetrics",
  "serviceOfferings",
  "technicalCapabilities",
  "deliveryCapabilities",
  "expertiseAreas",
  "clientEngagementModel",
  "projectMethodology",
  "communicationStyle",
  "uniqueValuePropositions",
  "marketPositioning",
  "targetSegments",
  "qualityStandards",
  "businessApproach",
  "industrySpecializations",
  "targetMarkets",
  "createdAt",
  "updatedAt"
) VALUES (
  '01K5D01YCQJ9TJ7CT4DZDE79T1_COMPANY',
  '01K5D01YCQJ9TJ7CT4DZDE79T1',
  'TOP Engineers Plus',
  'TOP Engineers Plus PLLC',
  'TOP Engineers Plus',
  'https://topengineersplus.com',
  'info@topengineersplus.com',
  '(210) 416-4808',
  '1100 West 116th Avenue',
  'Westminster',
  'CO',
  'United States',
  '80234',
  'Communications Engineering',
  'Professional Services',
  'Small-Medium',
  'TOP Engineers Plus is a competitive Communications Engineering firm specializing in critical infrastructure and broadband deployment. We simplify complex communication engineering challenges, breaking them down into clear, actionable tasks for thriving communities.',
  'Specializes in Communications technology, process development, and organizational alignment for a holistic project approach. Excels in deconstructing complex problems into actionable components, providing clients with strategic clarity and confidence in their decision-making processes.',
  ARRAY['Communications Engineering', 'Utility Infrastructure', 'Critical Infrastructure', 'Broadband Deployment', 'Engineering Consulting'],
  'Customer',
  'Premium',
  'Communications Engineering',
  ARRAY['Complex communication engineering challenges', 'Infrastructure deployment complexity', 'Organizational alignment issues', 'Process optimization needs'],
  ARRAY['Simplify complex challenges', 'Deliver strategic clarity', 'Provide comprehensive expertise', 'Ensure client satisfaction'],
  ARRAY['Complexity Simplified', 'Comprehensive Expertise', 'Strategic Clarity', 'Proven Track Record', 'Innovative Solutions', 'Efficient Delivery'],
  ARRAY['Infrastructure development growth', 'Digital transformation opportunities', 'Smart city initiatives', 'Broadband expansion projects'],
  'Established',
  ARRAY['Expand service offerings', 'Enhance client engagement', 'Develop new capabilities', 'Strengthen market position'],
  ARRAY['Client satisfaction', 'Project success rate', 'On-time delivery', 'Budget adherence'],
  ARRAY['Technology Expertise', 'Process Development', 'Organizational Alignment', 'Change Management', 'Strategic Consulting', 'Project Delivery'],
  ARRAY['Communications Technology', 'Process Development', 'Change Management', 'Workflow Optimization', 'Quality Assurance'],
  ARRAY['Timely Delivery', 'Budget-Friendly', 'Streamlined Processes', 'Efficient Implementation', 'Quality Assurance'],
  ARRAY['Critical Infrastructure', 'Broadband Deployment', 'Utility Communications', 'Smart City Technology', 'Digital Transformation'],
  'Client-Centric Approach',
  'Simplify, Optimize, Excel',
  'Professional',
  ARRAY['Complexity Simplified', 'Comprehensive Expertise', 'Strategic Clarity', 'Client-Centric Approach', 'Proven Track Record'],
  'Competitive Communications Engineering Firm',
  ARRAY['Utility Companies', 'Municipalities', 'Infrastructure Organizations', 'Engineering Firms'],
  ARRAY['Operational Excellence', 'Professionalism', 'Integrity', 'Quality Standards', 'Client Satisfaction'],
  'Turn complex challenges into simple, actionable solutions for thriving communities',
  ARRAY['Communications Engineering', 'Utility Infrastructure', 'Critical Infrastructure', 'Broadband Deployment'],
  ARRAY['Utility Companies', 'Municipalities', 'Infrastructure Organizations', 'Engineering Partners'],
  NOW(),
  NOW()
) ON CONFLICT ("id") DO UPDATE SET
  "name" = EXCLUDED."name",
  "legalName" = EXCLUDED."legalName",
  "tradingName" = EXCLUDED."tradingName",
  "website" = EXCLUDED."website",
  "email" = EXCLUDED."email",
  "phone" = EXCLUDED."phone",
  "address" = EXCLUDED."address",
  "city" = EXCLUDED."city",
  "state" = EXCLUDED."state",
  "country" = EXCLUDED."country",
  "postalCode" = EXCLUDED."postalCode",
  "industry" = EXCLUDED."industry",
  "sector" = EXCLUDED."sector",
  "size" = EXCLUDED."size",
  "description" = EXCLUDED."description",
  "notes" = EXCLUDED."notes",
  "tags" = EXCLUDED."tags",
  "accountType" = EXCLUDED."accountType",
  "tier" = EXCLUDED."tier",
  "vertical" = EXCLUDED."vertical",
  "businessChallenges" = EXCLUDED."businessChallenges",
  "businessPriorities" = EXCLUDED."businessPriorities",
  "competitiveAdvantages" = EXCLUDED."competitiveAdvantages",
  "growthOpportunities" = EXCLUDED."growthOpportunities",
  "marketPosition" = EXCLUDED."marketPosition",
  "strategicInitiatives" = EXCLUDED."strategicInitiatives",
  "successMetrics" = EXCLUDED."successMetrics",
  "serviceOfferings" = EXCLUDED."serviceOfferings",
  "technicalCapabilities" = EXCLUDED."technicalCapabilities",
  "deliveryCapabilities" = EXCLUDED."deliveryCapabilities",
  "expertiseAreas" = EXCLUDED."expertiseAreas",
  "clientEngagementModel" = EXCLUDED."clientEngagementModel",
  "projectMethodology" = EXCLUDED."projectMethodology",
  "communicationStyle" = EXCLUDED."communicationStyle",
  "uniqueValuePropositions" = EXCLUDED."uniqueValuePropositions",
  "marketPositioning" = EXCLUDED."marketPositioning",
  "targetSegments" = EXCLUDED."targetSegments",
  "qualityStandards" = EXCLUDED."qualityStandards",
  "businessApproach" = EXCLUDED."businessApproach",
  "industrySpecializations" = EXCLUDED."industrySpecializations",
  "targetMarkets" = EXCLUDED."targetMarkets",
  "updatedAt" = NOW();

-- Create industry intelligence records for TOP Engineers Plus
INSERT INTO "industry_intelligence" (
  "id",
  "workspaceId",
  "industryId",
  "intelligenceType",
  "title",
  "content",
  "summary",
  "source",
  "publishedDate",
  "relevanceScore",
  "impactLevel",
  "tags",
  "companies",
  "salesOpportunity",
  "actionableInsights",
  "isActive",
  "isVerified",
  "createdAt",
  "updatedAt"
) VALUES (
  '01K5D01YCQJ9TJ7CT4DZDE79T1_INTEL_1',
  '01K5D01YCQJ9TJ7CT4DZDE79T1',
  (SELECT "id" FROM "industries" WHERE "name" = 'Communications Engineering' AND "workspaceId" = '01K5D01YCQJ9TJ7CT4DZDE79T1' LIMIT 1),
  'Market Trend',
  'Critical Infrastructure Communications Demand Growing',
  'The demand for critical infrastructure communications is growing rapidly as utilities and municipalities modernize their systems. This presents significant opportunities for Communications Engineering firms like TOP Engineers Plus.',
  'Growing market demand for critical infrastructure communications solutions',
  'Industry Analysis',
  NOW(),
  0.9,
  'High',
  ARRAY['Critical Infrastructure', 'Communications', 'Market Growth', 'Utilities'],
  ARRAY['TOP Engineers Plus'],
  true,
  ARRAY['Focus on utility communications projects', 'Develop smart city solutions', 'Expand broadband deployment services'],
  true,
  true,
  NOW(),
  NOW()
), (
  '01K5D01YCQJ9TJ7CT4DZDE79T1_INTEL_2',
  '01K5D01YCQJ9TJ7CT4DZDE79T1',
  (SELECT "id" FROM "industries" WHERE "name" = 'Communications Engineering' AND "workspaceId" = '01K5D01YCQJ9TJ7CT4DZDE79T1' LIMIT 1),
  'Competitive Intelligence',
  'TOP Engineers Plus Competitive Advantages',
  'TOP Engineers Plus differentiates itself through its ability to simplify complex communication engineering challenges and provide strategic clarity. Their client-centric approach and proven track record position them well in the market.',
  'TOP Engineers Plus has strong competitive positioning in Communications Engineering',
  'Internal Analysis',
  NOW(),
  0.95,
  'High',
  ARRAY['Competitive Advantage', 'Market Position', 'Value Proposition'],
  ARRAY['TOP Engineers Plus'],
  true,
  ARRAY['Leverage complexity simplification expertise', 'Emphasize strategic clarity in proposals', 'Highlight client-centric approach'],
  true,
  true,
  NOW(),
  NOW()
) ON CONFLICT ("id") DO NOTHING;

-- Create market intelligence records
INSERT INTO "marketIntelligence" (
  "id",
  "workspaceId",
  "title",
  "description",
  "insights",
  "source",
  "relevance",
  "tags",
  "isActive",
  "createdAt",
  "updatedAt"
) VALUES (
  '01K5D01YCQJ9TJ7CT4DZDE79T1_MARKET_1',
  '01K5D01YCQJ9TJ7CT4DZDE79T1',
  'Communications Engineering Market Opportunities',
  'Analysis of market opportunities in Communications Engineering for TOP Engineers Plus',
  ARRAY['Utility infrastructure modernization', 'Smart city initiatives', 'Broadband expansion projects', 'Digital transformation needs'],
  'Market Research',
  'high',
  ARRAY['Market Opportunity', 'Communications Engineering', 'Infrastructure'],
  true,
  NOW(),
  NOW()
), (
  '01K5D01YCQJ9TJ7CT4DZDE79T1_MARKET_2',
  '01K5D01YCQJ9TJ7CT4DZDE79T1',
  'TOP Engineers Plus Value Proposition Analysis',
  'Analysis of TOP Engineers Plus unique value propositions and market positioning',
  ARRAY['Complexity simplification expertise', 'Strategic clarity delivery', 'Client-centric approach', 'Proven track record'],
  'Internal Analysis',
  'high',
  ARRAY['Value Proposition', 'Competitive Advantage', 'Market Position'],
  true,
  NOW(),
  NOW()
) ON CONFLICT ("id") DO NOTHING;

-- Update existing companies in the workspace to have proper industry classification
UPDATE "companies" 
SET 
  "industry" = 'Communications Engineering',
  "sector" = 'Professional Services',
  "tags" = ARRAY['Communications Engineering', 'Utility Infrastructure', 'Critical Infrastructure', 'Broadband Deployment'],
  "updatedAt" = NOW()
WHERE "workspaceId" = '01K5D01YCQJ9TJ7CT4DZDE79T1' 
  AND "industry" IS NULL OR "industry" = 'Engineering';

-- Create a summary of the enrichment
SELECT 
  'TOP Engineers Plus Data Enrichment Complete' as status,
  COUNT(*) as companies_updated,
  (SELECT COUNT(*) FROM "companies" WHERE "workspaceId" = '01K5D01YCQJ9TJ7CT4DZDE79T1') as total_companies,
  (SELECT COUNT(*) FROM "people" WHERE "workspaceId" = '01K5D01YCQJ9TJ7CT4DZDE79T1') as total_people
FROM "companies" 
WHERE "workspaceId" = '01K5D01YCQJ9TJ7CT4DZDE79T1';
