/**
 * 🎯 RANKING EVENT TYPES
 * 
 * Centralized event type definitions and constants
 */

export const RANKING_EVENT_TYPES = {
  // Contact Activities
  CONTACT_CREATED: 'contact_created',
  CONTACT_UPDATED: 'contact_updated',
  CONTACT_VIEWED: 'contact_viewed',
  CONTACT_EMAILED: 'contact_emailed',
  CONTACT_CALLED: 'contact_called',
  CONTACT_MEETING_SCHEDULED: 'contact_meeting_scheduled',
  
  // Lead Activities
  LEAD_CREATED: 'lead_created',
  LEAD_QUALIFIED: 'lead_qualified',
  LEAD_CONVERTED: 'lead_converted',
  LEAD_COMPLETED: 'lead_completed',
  
  // Opportunity Activities
  OPPORTUNITY_CREATED: 'opportunity_created',
  OPPORTUNITY_STAGE_CHANGED: 'opportunity_stage_changed',
  OPPORTUNITY_AMOUNT_CHANGED: 'opportunity_amount_changed',
  OPPORTUNITY_WON: 'opportunity_won',
  OPPORTUNITY_LOST: 'opportunity_lost',
  
  // Prospect Activities
  PROSPECT_CREATED: 'prospect_created',
  PROSPECT_ENGAGED: 'prospect_engaged',
  PROSPECT_QUALIFIED: 'prospect_qualified',
  
  // Email Engagement
  EMAIL_SENT: 'email_sent',
  EMAIL_OPENED: 'email_opened',
  EMAIL_CLICKED: 'email_clicked',
  EMAIL_REPLIED: 'email_replied',
  
  // External Signals
  BUYING_SIGNAL: 'buying_signal',
  COMPANY_NEWS: 'company_news',
  EXECUTIVE_CHANGE: 'executive_change',
  FUNDING_ROUND: 'funding_round'
} as const;

export type RankingEventType = typeof RANKING_EVENT_TYPES[keyof typeof RANKING_EVENT_TYPES];

// Event impact weights (higher = more important)
export const EVENT_IMPACT_WEIGHTS: Record<RankingEventType, number> = {
  // High Impact Events (Major rank changes)
  [RANKING_EVENT_TYPES.OPPORTUNITY_WON]: 100,
  [RANKING_EVENT_TYPES.OPPORTUNITY_STAGE_CHANGED]: 50,
  [RANKING_EVENT_TYPES.EMAIL_REPLIED]: 40,
  [RANKING_EVENT_TYPES.CONTACT_MEETING_SCHEDULED]: 35,
  [RANKING_EVENT_TYPES.LEAD_CONVERTED]: 30,
  
  // Medium Impact Events (Moderate rank changes)
  [RANKING_EVENT_TYPES.EMAIL_OPENED]: 20,
  [RANKING_EVENT_TYPES.EMAIL_CLICKED]: 25,
  [RANKING_EVENT_TYPES.LEAD_QUALIFIED]: 30,
  [RANKING_EVENT_TYPES.CONTACT_VIEWED]: 10,
  [RANKING_EVENT_TYPES.CONTACT_EMAILED]: 15,
  [RANKING_EVENT_TYPES.CONTACT_CALLED]: 20,
  
  // Low Impact Events (Minor rank changes)
  [RANKING_EVENT_TYPES.EMAIL_SENT]: 5,
  [RANKING_EVENT_TYPES.CONTACT_CREATED]: 3,
  [RANKING_EVENT_TYPES.PROSPECT_CREATED]: 3,
  [RANKING_EVENT_TYPES.LEAD_CREATED]: 5,
  [RANKING_EVENT_TYPES.OPPORTUNITY_CREATED]: 8,
  
  // Default weights for other events
  [RANKING_EVENT_TYPES.CONTACT_UPDATED]: 5,
  [RANKING_EVENT_TYPES.OPPORTUNITY_AMOUNT_CHANGED]: 15,
  [RANKING_EVENT_TYPES.OPPORTUNITY_LOST]: -20,
  [RANKING_EVENT_TYPES.PROSPECT_ENGAGED]: 8,
  [RANKING_EVENT_TYPES.PROSPECT_QUALIFIED]: 12,
  [RANKING_EVENT_TYPES.LEAD_COMPLETED]: 10,
  [RANKING_EVENT_TYPES.BUYING_SIGNAL]: 30,
  [RANKING_EVENT_TYPES.COMPANY_NEWS]: 5,
  [RANKING_EVENT_TYPES.EXECUTIVE_CHANGE]: 15,
  [RANKING_EVENT_TYPES.FUNDING_ROUND]: 25
};

// Event categories for filtering and processing
export const EVENT_CATEGORIES = {
  HIGH_IMPACT: [
    RANKING_EVENT_TYPES.OPPORTUNITY_WON,
    RANKING_EVENT_TYPES.OPPORTUNITY_STAGE_CHANGED,
    RANKING_EVENT_TYPES.EMAIL_REPLIED,
    RANKING_EVENT_TYPES.CONTACT_MEETING_SCHEDULED,
    RANKING_EVENT_TYPES.LEAD_CONVERTED
  ],
  
  MEDIUM_IMPACT: [
    RANKING_EVENT_TYPES.EMAIL_OPENED,
    RANKING_EVENT_TYPES.EMAIL_CLICKED,
    RANKING_EVENT_TYPES.LEAD_QUALIFIED,
    RANKING_EVENT_TYPES.CONTACT_VIEWED,
    RANKING_EVENT_TYPES.CONTACT_EMAILED,
    RANKING_EVENT_TYPES.CONTACT_CALLED
  ],
  
  LOW_IMPACT: [
    RANKING_EVENT_TYPES.EMAIL_SENT,
    RANKING_EVENT_TYPES.CONTACT_CREATED,
    RANKING_EVENT_TYPES.PROSPECT_CREATED,
    RANKING_EVENT_TYPES.LEAD_CREATED,
    RANKING_EVENT_TYPES.OPPORTUNITY_CREATED
  ],
  
  NEGATIVE_IMPACT: [
    RANKING_EVENT_TYPES.OPPORTUNITY_LOST
  ]
} as const;

// Event processing priorities
export const EVENT_PRIORITIES = {
  CRITICAL: 1,    // Process immediately
  HIGH: 2,        // Process within 1 minute
  MEDIUM: 3,      // Process within 5 minutes
  LOW: 4          // Process within 15 minutes
} as const;

// Event priority mapping
export const EVENT_PRIORITY_MAP: Record<RankingEventType, number> = {
  [RANKING_EVENT_TYPES.OPPORTUNITY_WON]: EVENT_PRIORITIES.CRITICAL,
  [RANKING_EVENT_TYPES.OPPORTUNITY_LOST]: EVENT_PRIORITIES.CRITICAL,
  [RANKING_EVENT_TYPES.EMAIL_REPLIED]: EVENT_PRIORITIES.HIGH,
  [RANKING_EVENT_TYPES.CONTACT_MEETING_SCHEDULED]: EVENT_PRIORITIES.HIGH,
  [RANKING_EVENT_TYPES.LEAD_CONVERTED]: EVENT_PRIORITIES.HIGH,
  [RANKING_EVENT_TYPES.OPPORTUNITY_STAGE_CHANGED]: EVENT_PRIORITIES.HIGH,
  [RANKING_EVENT_TYPES.EMAIL_CLICKED]: EVENT_PRIORITIES.MEDIUM,
  [RANKING_EVENT_TYPES.EMAIL_OPENED]: EVENT_PRIORITIES.MEDIUM,
  [RANKING_EVENT_TYPES.CONTACT_CALLED]: EVENT_PRIORITIES.MEDIUM,
  [RANKING_EVENT_TYPES.EMAIL_SENT]: EVENT_PRIORITIES.LOW,
  [RANKING_EVENT_TYPES.CONTACT_CREATED]: EVENT_PRIORITIES.LOW,
  [RANKING_EVENT_TYPES.PROSPECT_CREATED]: EVENT_PRIORITIES.LOW,
  [RANKING_EVENT_TYPES.LEAD_CREATED]: EVENT_PRIORITIES.LOW,
  [RANKING_EVENT_TYPES.OPPORTUNITY_CREATED]: EVENT_PRIORITIES.LOW,
  [RANKING_EVENT_TYPES.CONTACT_UPDATED]: EVENT_PRIORITIES.LOW,
  [RANKING_EVENT_TYPES.OPPORTUNITY_AMOUNT_CHANGED]: EVENT_PRIORITIES.MEDIUM,
  [RANKING_EVENT_TYPES.PROSPECT_ENGAGED]: EVENT_PRIORITIES.MEDIUM,
  [RANKING_EVENT_TYPES.PROSPECT_QUALIFIED]: EVENT_PRIORITIES.MEDIUM,
  [RANKING_EVENT_TYPES.LEAD_COMPLETED]: EVENT_PRIORITIES.MEDIUM,
  [RANKING_EVENT_TYPES.BUYING_SIGNAL]: EVENT_PRIORITIES.HIGH,
  [RANKING_EVENT_TYPES.COMPANY_NEWS]: EVENT_PRIORITIES.LOW,
  [RANKING_EVENT_TYPES.EXECUTIVE_CHANGE]: EVENT_PRIORITIES.MEDIUM,
  [RANKING_EVENT_TYPES.FUNDING_ROUND]: EVENT_PRIORITIES.MEDIUM,
  [RANKING_EVENT_TYPES.LEAD_QUALIFIED]: EVENT_PRIORITIES.MEDIUM,
  [RANKING_EVENT_TYPES.CONTACT_VIEWED]: EVENT_PRIORITIES.LOW,
  [RANKING_EVENT_TYPES.CONTACT_EMAILED]: EVENT_PRIORITIES.MEDIUM
} as const;
