/**
 * Check if Southern Company has strategy data in the database
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function checkSouthernCompanyStrategy() {
  const companyId = '01K9QD2ST0C0TTG34EMRD3M69H';
  const companyName = 'Southern Company';

  try {
    console.log(`🔍 Checking strategy data for ${companyName} (${companyId})...\n`);

    // Get company with customFields
    const company = await prisma.companies.findUnique({
      where: { id: companyId },
      select: {
        id: true,
        name: true,
        customFields: true,
        descriptionEnriched: true,
        createdAt: true,
        updatedAt: true
      }
    });

    if (!company) {
      console.log('❌ Company not found in database');
      return;
    }

    console.log('✅ Company found:', {
      id: company.id,
      name: company.name,
      createdAt: company.createdAt,
      updatedAt: company.updatedAt,
      hasDescriptionEnriched: !!company.descriptionEnriched,
      descriptionEnrichedLength: company.descriptionEnriched?.length || 0
    });

    const customFields = company.customFields as any;
    
    console.log('\n📊 CustomFields Analysis:');
    console.log('  - Has customFields:', !!customFields);
    console.log('  - CustomFields keys:', customFields ? Object.keys(customFields) : 'none');
    
    if (customFields) {
      console.log('  - Has strategyData:', !!customFields.strategyData);
      console.log('  - Has intelligence:', !!customFields.intelligence);
      console.log('  - Has lastStrategyUpdate:', !!customFields.lastStrategyUpdate);
      
      if (customFields.strategyData) {
        const strategy = customFields.strategyData;
        console.log('\n✅ Strategy Data Found:');
        console.log('  - Strategy Summary:', strategy.strategySummary ? strategy.strategySummary.substring(0, 100) + '...' : 'missing');
        console.log('  - Archetype:', strategy.archetypeName || 'missing');
        console.log('  - Target Industry:', strategy.targetIndustry || 'missing');
        console.log('  - Generated At:', strategy.strategyGeneratedAt || 'missing');
        console.log('  - Generated By:', strategy.strategyGeneratedBy || 'missing');
        console.log('  - Has Situation:', !!strategy.situation);
        console.log('  - Has Complication:', !!strategy.complication);
        console.log('  - Has Future State:', !!strategy.futureState);
        console.log('  - Strategic Recommendations:', strategy.strategicRecommendations?.length || 0);
      } else {
        console.log('\n❌ No strategyData found in customFields');
      }
      
      if (customFields.intelligence) {
        console.log('\n✅ Intelligence Data Found:');
        console.log('  - Intelligence Version:', customFields.intelligenceVersion || 'unknown');
        console.log('  - Intelligence Type:', typeof customFields.intelligence);
        if (typeof customFields.intelligence === 'string') {
          console.log('  - Intelligence Length:', customFields.intelligence.length);
        }
      } else {
        console.log('\n❌ No intelligence data found in customFields');
      }
    } else {
      console.log('\n❌ No customFields found');
    }

    // Check if there are any related records that might have strategy data
    console.log('\n🔍 Checking related data...');
    const peopleCount = await prisma.people.count({
      where: {
        companyId: companyId,
        deletedAt: null
      }
    });
    console.log(`  - People count: ${peopleCount}`);

    // Check for any buyer groups
    const buyerGroupsCount = await prisma.buyerGroups.count({
      where: {
        companyName: company.name
      }
    });
    console.log(`  - Buyer groups count: ${buyerGroupsCount}`);

  } catch (error) {
    console.error('❌ Error checking company strategy:', error);
  } finally {
    await prisma.$disconnect();
  }
}

checkSouthernCompanyStrategy();

