/**
 * E2E Tests for Deep Value Reports
 * 
 * Tests complete user journeys for report generation, viewing, and editing
 */

import { test, expect } from '@playwright/test';

// Test data
const TEST_PERSON = {
  id: 'test-person-123',
  name: 'John Smith',
  email: 'john.smith@example.com',
  company: 'TechCorp Inc.',
  title: 'Senior Software Engineer'
};

const TEST_COMPANY = {
  id: 'test-company-456',
  name: 'TechCorp Inc.',
  industry: 'Technology',
  size: '201-500 employees'
};

test.describe('Deep Value Reports E2E', () => {
  test.beforeEach(async ({ page }) => {
    // Navigate to the application
    await page.goto('http://localhost:3000');
    
    // Mock authentication
    await page.evaluate(() => {
      localStorage.setItem('auth-token', 'test-token');
      localStorage.setItem('user', JSON.stringify({
        id: 'test-user-123',
        email: 'test@example.com',
        name: 'Test User',
        workspaceId: 'test-workspace-123'
      }));
    });

    // Mock API responses
    await page.route('**/api/atrium/reports**', async (route) => {
      const url = route.request().url();
      const method = route.request().method();

      if (method === 'GET') {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            success: true,
            data: [],
            meta: { pagination: { page: 1, limit: 10, totalCount: 0, totalPages: 0 } }
          })
        });
      } else if (method === 'POST') {
        await route.fulfill({
          status: 201,
          contentType: 'application/json',
          body: JSON.stringify({
            success: true,
            data: {
              id: 'report-123',
              type: 'executive_summary',
              title: 'Executive Summary for John Smith',
              content: '# Executive Summary\n\nThis is a test executive summary.',
              status: 'completed',
              recordType: 'people',
              recordId: TEST_PERSON.id,
              recordName: TEST_PERSON.name,
              atriumDocumentId: 'atrium-doc-123',
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString()
            }
          })
        });
      }
    });

    // Mock AI service
    await page.route('**/api/ai/generate**', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          success: true,
          data: {
            content: '# Executive Summary\n\nThis is a test executive summary generated by AI.'
          }
        })
      });
    });
  });

  test.describe('Report Generation via AI Chat', () => {
    test('should generate report when user types request in AI chat', async ({ page }) => {
      // Navigate to a person record
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      
      // Wait for the page to load
      await page.waitForSelector('[data-testid="ai-chat-input"]');
      
      // Type report generation request
      const chatInput = page.locator('[data-testid="ai-chat-input"]');
      await chatInput.fill('Create me a deep value report for this person');
      await chatInput.press('Enter');
      
      // Wait for AI response
      await page.waitForSelector('[data-testid="ai-response"]');
      
      // Verify AI response contains report generation message
      const aiResponse = page.locator('[data-testid="ai-response"]').last();
      await expect(aiResponse).toContainText('I\'ll generate a deep value report for John Smith');
      
      // Wait for report generation to complete
      await page.waitForSelector('[data-testid="report-generated"]', { timeout: 10000 });
      
      // Verify report is displayed in middle panel
      await expect(page.locator('[data-testid="report-view"]')).toBeVisible();
      await expect(page.locator('h1')).toContainText('Executive Summary');
    });

    test('should show quick action button for report generation', async ({ page }) => {
      // Navigate to a person record
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      
      // Wait for quick actions to load
      await page.waitForSelector('[data-testid="quick-actions"]');
      
      // Verify quick action button exists
      const quickAction = page.locator('[data-testid="quick-actions"]').getByText('Create me a deep value report');
      await expect(quickAction).toBeVisible();
      
      // Click quick action
      await quickAction.click();
      
      // Wait for report generation
      await page.waitForSelector('[data-testid="report-generated"]', { timeout: 10000 });
      
      // Verify report is displayed
      await expect(page.locator('[data-testid="report-view"]')).toBeVisible();
    });
  });

  test.describe('Report Generation via Value Tab', () => {
    test('should generate report from Value tab', async ({ page }) => {
      // Navigate to a person record
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      
      // Click on Value tab
      await page.click('[data-testid="value-tab"]');
      
      // Wait for Value tab to load
      await page.waitForSelector('[data-testid="report-cards"]');
      
      // Verify all report types are displayed
      await expect(page.locator('[data-testid="report-card"]')).toHaveCount(5);
      await expect(page.getByText('Executive Summary')).toBeVisible();
      await expect(page.getByText('Competitive Analysis')).toBeVisible();
      await expect(page.getByText('Value Proposition')).toBeVisible();
      await expect(page.getByText('Engagement Strategy')).toBeVisible();
      await expect(page.getByText('Risk Assessment')).toBeVisible();
      
      // Click on Executive Summary report card
      const executiveSummaryCard = page.locator('[data-testid="report-card"]').first();
      await executiveSummaryCard.click();
      
      // Wait for report generation
      await page.waitForSelector('[data-testid="report-generated"]', { timeout: 10000 });
      
      // Verify report opens in full-screen view
      await expect(page.locator('[data-testid="report-view"]')).toBeVisible();
      await expect(page.locator('h1')).toContainText('Executive Summary');
    });

    test('should show report status indicators', async ({ page }) => {
      // Navigate to a person record
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      
      // Click on Value tab
      await page.click('[data-testid="value-tab"]');
      
      // Wait for Value tab to load
      await page.waitForSelector('[data-testid="report-cards"]');
      
      // Verify all reports show "Generate" status initially
      const generateButtons = page.locator('[data-testid="generate-button"]');
      await expect(generateButtons).toHaveCount(5);
      
      // Click generate on first report
      await generateButtons.first().click();
      
      // Verify status changes to "Generating..."
      await expect(page.locator('[data-testid="generating-status"]')).toBeVisible();
      
      // Wait for completion
      await page.waitForSelector('[data-testid="completed-status"]', { timeout: 10000 });
      
      // Verify status changes to "Completed"
      await expect(page.locator('[data-testid="completed-status"]')).toBeVisible();
      await expect(page.locator('[data-testid="view-report-button"]')).toBeVisible();
    });
  });

  test.describe('Report Viewing and Navigation', () => {
    test('should display report with proper breadcrumb navigation', async ({ page }) => {
      // Navigate to a person record
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      
      // Generate a report
      await page.click('[data-testid="value-tab"]');
      await page.waitForSelector('[data-testid="report-cards"]');
      await page.locator('[data-testid="report-card"]').first().click();
      await page.waitForSelector('[data-testid="report-generated"]', { timeout: 10000 });
      
      // Verify breadcrumb navigation
      const breadcrumb = page.locator('[data-testid="breadcrumb"]');
      await expect(breadcrumb).toContainText(TEST_PERSON.name);
      await expect(breadcrumb).toContainText('Executive Summary');
      
      // Verify back button works
      const backButton = page.locator('[data-testid="back-button"]');
      await expect(backButton).toBeVisible();
      await backButton.click();
      
      // Should return to record view
      await expect(page.locator('[data-testid="record-view"]')).toBeVisible();
    });

    test('should display report content with proper formatting', async ({ page }) => {
      // Navigate to a person record
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      
      // Generate a report
      await page.click('[data-testid="value-tab"]');
      await page.waitForSelector('[data-testid="report-cards"]');
      await page.locator('[data-testid="report-card"]').first().click();
      await page.waitForSelector('[data-testid="report-generated"]', { timeout: 10000 });
      
      // Verify report content is displayed
      const reportContent = page.locator('[data-testid="report-content"]');
      await expect(reportContent).toBeVisible();
      await expect(reportContent).toContainText('Executive Summary');
      await expect(reportContent).toContainText('This is a test executive summary');
      
      // Verify markdown formatting
      await expect(reportContent.locator('h1')).toContainText('Executive Summary');
    });
  });

  test.describe('Report Editing', () => {
    test('should allow inline editing of report content', async ({ page }) => {
      // Navigate to a person record and generate report
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      await page.click('[data-testid="value-tab"]');
      await page.waitForSelector('[data-testid="report-cards"]');
      await page.locator('[data-testid="report-card"]').first().click();
      await page.waitForSelector('[data-testid="report-generated"]', { timeout: 10000 });
      
      // Click edit button
      const editButton = page.locator('[data-testid="edit-button"]');
      await editButton.click();
      
      // Verify edit mode is activated
      await expect(page.locator('[data-testid="edit-mode"]')).toBeVisible();
      await expect(page.locator('[data-testid="save-button"]')).toBeVisible();
      await expect(page.locator('[data-testid="cancel-button"]')).toBeVisible();
      
      // Edit content
      const contentEditor = page.locator('[data-testid="content-editor"]');
      await contentEditor.fill('# Executive Summary\n\nEdited content');
      
      // Save changes
      await page.click('[data-testid="save-button"]');
      
      // Verify changes are saved
      await expect(page.locator('[data-testid="report-content"]')).toContainText('Edited content');
    });

    test('should allow AI-powered editing', async ({ page }) => {
      // Navigate to a person record and generate report
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      await page.click('[data-testid="value-tab"]');
      await page.waitForSelector('[data-testid="report-cards"]');
      await page.locator('[data-testid="report-card"]').first().click();
      await page.waitForSelector('[data-testid="report-generated"]', { timeout: 10000 });
      
      // Click AI edit button
      const aiEditButton = page.locator('[data-testid="ai-edit-button"]');
      await aiEditButton.click();
      
      // Verify AI edit input appears
      const aiEditInput = page.locator('[data-testid="ai-edit-input"]');
      await expect(aiEditInput).toBeVisible();
      
      // Enter edit instruction
      await aiEditInput.fill('Make this more concise');
      
      // Submit edit request
      await page.click('[data-testid="apply-edit-button"]');
      
      // Wait for AI processing
      await page.waitForSelector('[data-testid="ai-processing"]');
      
      // Wait for edit to complete
      await page.waitForSelector('[data-testid="edit-completed"]', { timeout: 10000 });
      
      // Verify content was updated
      await expect(page.locator('[data-testid="report-content"]')).toContainText('concise');
    });
  });

  test.describe('Report Sharing', () => {
    test('should allow sharing of reports', async ({ page }) => {
      // Navigate to a person record and generate report
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      await page.click('[data-testid="value-tab"]');
      await page.waitForSelector('[data-testid="report-cards"]');
      await page.locator('[data-testid="report-card"]').first().click();
      await page.waitForSelector('[data-testid="report-generated"]', { timeout: 10000 });
      
      // Click share button
      const shareButton = page.locator('[data-testid="share-button"]');
      await shareButton.click();
      
      // Verify share modal appears
      await expect(page.locator('[data-testid="share-modal"]')).toBeVisible();
      
      // Verify share URL is generated
      const shareUrl = page.locator('[data-testid="share-url"]');
      await expect(shareUrl).toBeVisible();
      await expect(shareUrl).toHaveValue(/http:\/\/localhost:3000\/share\/report\/.+/);
      
      // Test copy to clipboard
      const copyButton = page.locator('[data-testid="copy-button"]');
      await copyButton.click();
      
      // Verify copy confirmation
      await expect(page.locator('[data-testid="copy-confirmation"]')).toBeVisible();
    });
  });

  test.describe('Speedrun Integration', () => {
    test('should work with speedrun navigation', async ({ page }) => {
      // Navigate to speedrun sprint
      await page.goto('http://localhost:3000/adrata/speedrun/sprint');
      
      // Wait for speedrun data to load
      await page.waitForSelector('[data-testid="speedrun-records"]');
      
      // Click on first person record
      const firstRecord = page.locator('[data-testid="speedrun-record"]').first();
      await firstRecord.click();
      
      // Verify URL updates to individual person
      await expect(page).toHaveURL(/\/speedrun\/.+-.+/);
      
      // Navigate to Value tab
      await page.click('[data-testid="value-tab"]');
      
      // Generate a report
      await page.waitForSelector('[data-testid="report-cards"]');
      await page.locator('[data-testid="report-card"]').first().click();
      await page.waitForSelector('[data-testid="report-generated"]', { timeout: 10000 });
      
      // Verify report is displayed
      await expect(page.locator('[data-testid="report-view"]')).toBeVisible();
    });

    test('should maintain speedrun context when navigating between people', async ({ page }) => {
      // Navigate to speedrun sprint
      await page.goto('http://localhost:3000/adrata/speedrun/sprint');
      
      // Wait for speedrun data to load
      await page.waitForSelector('[data-testid="speedrun-records"]');
      
      // Click on first person
      const firstRecord = page.locator('[data-testid="speedrun-record"]').first();
      await firstRecord.click();
      
      // Verify URL updates
      await expect(page).toHaveURL(/\/speedrun\/.+-.+/);
      
      // Use Previous/Next buttons
      const nextButton = page.locator('[data-testid="next-button"]');
      if (await nextButton.isVisible()) {
        await nextButton.click();
        
        // Verify URL updates to next person
        await expect(page).toHaveURL(/\/speedrun\/.+-.+/);
      }
    });
  });

  test.describe('Error Handling', () => {
    test('should handle AI service errors gracefully', async ({ page }) => {
      // Mock AI service error
      await page.route('**/api/ai/generate**', async (route) => {
        await route.fulfill({
          status: 500,
          contentType: 'application/json',
          body: JSON.stringify({
            success: false,
            error: 'AI service unavailable'
          })
        });
      });

      // Navigate to a person record
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      
      // Try to generate report
      await page.click('[data-testid="value-tab"]');
      await page.waitForSelector('[data-testid="report-cards"]');
      await page.locator('[data-testid="report-card"]').first().click();
      
      // Verify error message is displayed
      await expect(page.locator('[data-testid="error-message"]')).toBeVisible();
      await expect(page.locator('[data-testid="error-message"]')).toContainText('Error generating report');
    });

    test('should handle network errors gracefully', async ({ page }) => {
      // Mock network error
      await page.route('**/api/atrium/reports**', async (route) => {
        await route.abort('failed');
      });

      // Navigate to a person record
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      
      // Try to generate report
      await page.click('[data-testid="value-tab"]');
      await page.waitForSelector('[data-testid="report-cards"]');
      await page.locator('[data-testid="report-card"]').first().click();
      
      // Verify error message is displayed
      await expect(page.locator('[data-testid="error-message"]')).toBeVisible();
    });
  });

  test.describe('Accessibility', () => {
    test('should be keyboard navigable', async ({ page }) => {
      // Navigate to a person record
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      
      // Test keyboard navigation
      await page.keyboard.press('Tab');
      await page.keyboard.press('Tab');
      await page.keyboard.press('Tab');
      
      // Should be able to navigate to Value tab
      const valueTab = page.locator('[data-testid="value-tab"]');
      await expect(valueTab).toBeFocused();
      
      // Press Enter to activate tab
      await page.keyboard.press('Enter');
      
      // Wait for Value tab to load
      await page.waitForSelector('[data-testid="report-cards"]');
      
      // Tab to first report card
      await page.keyboard.press('Tab');
      const firstCard = page.locator('[data-testid="report-card"]').first();
      await expect(firstCard).toBeFocused();
      
      // Press Enter to generate report
      await page.keyboard.press('Enter');
      
      // Wait for report generation
      await page.waitForSelector('[data-testid="report-generated"]', { timeout: 10000 });
    });

    test('should have proper ARIA labels', async ({ page }) => {
      // Navigate to a person record
      await page.goto(`http://localhost:3000/adrata/people/${TEST_PERSON.id}`);
      
      // Check ARIA labels on buttons
      const generateButton = page.locator('[data-testid="generate-button"]').first();
      await expect(generateButton).toHaveAttribute('aria-label');
      
      const editButton = page.locator('[data-testid="edit-button"]').first();
      await expect(editButton).toHaveAttribute('aria-label');
      
      const shareButton = page.locator('[data-testid="share-button"]').first();
      await expect(shareButton).toHaveAttribute('aria-label');
    });
  });
});
