export const winningVariantCompanies = [
  {
    id: 'company_1',
    workspaceId: 'demo-workspace-2025',
    assignedUserId: null,
    name: 'Match Group',
    legalName: 'Match Group, Inc.',
    tradingName: 'Match.com',
    localName: null,
    website: 'https://match.com',
    email: 'contact@match.com',
    phone: '+1-214-576-9352',
    fax: null,
    address: '8750 North Central Expressway',
    city: 'Dallas',
    state: 'TX',
    country: 'United States',
    postalCode: '75231',
    industry: 'Technology',
    sector: 'Online Dating',
    size: '1000-5000',
    revenue: 3200000000.00,
    currency: 'USD',
    registrationNumber: 'MG-2023-001',
    taxId: '75-1234567',
    vatNumber: null,
    description: 'Leading online dating platform with multiple brands including Match.com, Tinder, and Hinge',
    notes: 'High-value prospect with significant e-commerce conversion optimization needs',
    tags: ['e-commerce', 'dating', 'high-value', 'conversion-optimization'],
    customFields: {
      snowflake: {
        isCustomer: true,
        usage: 'Data warehouse and analytics platform',
        implementationDate: '2021-08-20',
        primaryUseCase: 'User behavior analytics and matching algorithm optimization',
        dataVolume: 'Very High',
        notes: 'Using Snowflake for user interaction data, matching algorithms, and conversion funnel analysis across multiple dating platforms'
      }
    },
    preferredLanguage: 'en',
    timezone: 'America/Chicago',
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    accountType: 'enterprise',
    primaryContact: 'Sarah Johnson',
    tier: 'A',
    externalId: 'MG-001',
    vertical: 'Online Dating',
    zohoId: null,
    isDemoData: true,
    demoScenarioId: 'winning-variant'
  },
  {
    id: 'company_2',
    workspaceId: 'demo-workspace-2025',
    assignedUserId: null,
    name: 'Brex',
    legalName: 'Brex Inc.',
    tradingName: 'Brex',
    localName: null,
    website: 'https://brex.com',
    email: 'contact@brex.com',
    phone: '+1-415-967-0000',
    fax: null,
    address: '1 Hacker Way',
    city: 'San Francisco',
    state: 'CA',
    country: 'United States',
    postalCode: '94105',
    industry: 'Financial Technology',
    sector: 'FinTech',
    size: '500-1000',
    revenue: 500000000.00,
    currency: 'USD',
    registrationNumber: 'BX-2023-002',
    taxId: '82-1234567',
    vatNumber: null,
    description: 'Corporate credit card and financial services platform for startups and enterprises',
    notes: 'Fast-growing fintech with complex conversion funnel optimization needs',
    tags: ['fintech', 'startup', 'credit-cards', 'conversion-optimization'],
    customFields: {
      snowflake: {
        isCustomer: true,
        usage: 'Data warehouse and analytics platform',
        implementationDate: '2020-11-10',
        primaryUseCase: 'Financial transaction analytics and risk assessment',
        dataVolume: 'High',
        notes: 'Using Snowflake for transaction monitoring, fraud detection, and customer spending pattern analysis'
      }
    },
    preferredLanguage: 'en',
    timezone: 'America/Los_Angeles',
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    accountType: 'enterprise',
    primaryContact: 'Michael Chen',
    tier: 'A',
    externalId: 'BX-002',
    vertical: 'FinTech',
    zohoId: null,
    isDemoData: true,
    demoScenarioId: 'winning-variant'
  },
  {
    id: 'company_3',
    workspaceId: 'demo-workspace-2025',
    assignedUserId: null,
    name: 'First Premier Bank',
    legalName: 'First Premier Bank',
    tradingName: 'First Premier',
    localName: null,
    website: 'https://firstpremier.com',
    email: 'contact@firstpremier.com',
    phone: '+1-605-338-8000',
    fax: null,
    address: '601 South Minnesota Avenue',
    city: 'Sioux Falls',
    state: 'SD',
    country: 'United States',
    postalCode: '57104',
    industry: 'Banking',
    sector: 'Financial Services',
    size: '1000-5000',
    revenue: 800000000.00,
    currency: 'USD',
    registrationNumber: 'FP-2023-003',
    taxId: '46-1234567',
    vatNumber: null,
    description: 'Regional bank specializing in credit cards and consumer banking services',
    notes: 'Traditional bank looking to optimize digital customer acquisition',
    tags: ['banking', 'credit-cards', 'digital-transformation', 'conversion-optimization'],
    customFields: {
      snowflake: {
        isCustomer: true,
        usage: 'Data warehouse and analytics platform',
        implementationDate: '2023-01-15',
        primaryUseCase: 'Regulatory compliance and customer analytics',
        dataVolume: 'Medium',
        notes: 'Using Snowflake for regulatory reporting, customer segmentation, and digital banking analytics'
      }
    },
    preferredLanguage: 'en',
    timezone: 'America/Chicago',
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    accountType: 'enterprise',
    primaryContact: 'David Wilson',
    tier: 'A',
    externalId: 'FP-003',
    vertical: 'Banking',
    zohoId: null,
    isDemoData: true,
    demoScenarioId: 'winning-variant'
  }
];