#!/bin/bash

# Ross-Dan Chat Production Deployment Fix
# Generated by fix-ross-dan-chat-production.ts

set -e

echo "🔧 Fixing Ross-Dan Chat Production Issues..."

# 1. Check if we have the Vercel CLI
if ! command -v vercel &> /dev/null; then
    echo "❌ Vercel CLI not found. Install with: npm i -g vercel"
    exit 1
fi

# 2. Set critical environment variables (CORRECT PUSHER CREDENTIALS)
echo "🔧 Setting Pusher environment variables..."
vercel env add PUSHER_APP_ID production <<< "2014946"
vercel env add PUSHER_KEY production <<< "1c5e2d82c19e713c07ff"
vercel env add PUSHER_SECRET production <<< "446caa0d73c1cbff6e97"
vercel env add PUSHER_CLUSTER production <<< "us3"
vercel env add NEXT_PUBLIC_PUSHER_KEY production <<< "1c5e2d82c19e713c07ff"
vercel env add NEXT_PUBLIC_PUSHER_CLUSTER production <<< "us3"

# 3. Set application URLs
echo "🌐 Setting application URLs..."
vercel env add NEXTAUTH_URL production <<< "https://adrata.vercel.app"
vercel env add NEXT_PUBLIC_APP_URL production <<< "https://adrata.vercel.app"
vercel env add NEXT_PUBLIC_API_BASE_URL production <<< "https://adrata.vercel.app"

# 4. Deploy with all API routes
echo "🚀 Deploying to production..."
vercel --prod

# 5. Test the deployment
echo "🧪 Testing deployment..."
sleep 10
curl -f "https://adrata.vercel.app/api/chat/ross-dan" || echo "⚠️ API test failed - check deployment"

echo "✅ Deployment complete!"
echo "🔗 Production URL: https://adrata.vercel.app"
echo "🧪 Test the Ross-Dan chat functionality"