"use client";

import React from 'react';
import Link from 'next/link';
import { BuyerGroupMemberCard } from '../../winning-variant/components/BuyerGroupMemberCard';

// Import data - will be generated by pipeline
import wguData from '../data/wgu-buyer-group-retention.json';

interface PainPoint {
  title: string;
  description: string;
  impact: string;
  urgency: 'high' | 'medium' | 'low';
}

interface BuyerGroupMember {
  name: string;
  title: string;
  department?: string;
  role: 'Decision Maker' | 'Champion' | 'Stakeholder' | 'Blocker' | 'Introducer';
  email?: string;
  phone?: string;
  linkedin?: string;
  influenceScore: number;
  confidence: number;
  painPoints?: PainPoint[];
  personalizedStrategy?: {
    situation: string;
    complication: string;
    futureState: string;
  };
  archetype?: {
    id: string;
    name: string;
    role: string;
    description: string;
    characteristics: {
      motivations: string[];
      concerns: string[];
      decisionMakingStyle: string;
      communicationStyle: string;
      keyNeeds: string[];
    };
  };
}

// Transform pipeline data to page format
function transformData(data: any) {
  const companyInfo = {
    name: data.company?.name || 'Western Governors University',
    website: data.company?.website || 'https://wgu.edu',
    industry: data.company?.industry || 'Education',
    size: data.company?.employeeCount ? `${data.company.employeeCount} employees` : 'Unknown',
    headquarters: 'Salt Lake City, Utah'
  };

  const buyerGroup = {
    totalMembers: data.buyerGroup?.totalMembers || 0,
    cohesionScore: data.buyerGroup?.cohesionScore || 0,
    overallConfidence: data.buyerGroup?.overallConfidence || 0,
    members: (data.buyerGroup?.members || []).map((member: any) => ({
      name: member.name,
      title: member.title,
      role: mapRole(member.role),
      archetype: member.archetype || generateArchetype(member),
      personalizedStrategy: member.personalizedStrategy || generateStrategy(member),
      contactInfo: {
        email: member.email,
        phone: member.phone,
        linkedin: member.linkedin
      },
      influenceScore: member.influenceScore || 0,
      confidence: member.confidence || 0,
      painPoints: member.painPoints || []
    }))
  };

  return { companyInfo, buyerGroup };
}

function mapRole(role: string): 'Decision Maker' | 'Champion' | 'Stakeholder' | 'Blocker' | 'Introducer' {
  const roleMap: Record<string, 'Decision Maker' | 'Champion' | 'Stakeholder' | 'Blocker' | 'Introducer'> = {
    'decision': 'Decision Maker',
    'champion': 'Champion',
    'stakeholder': 'Stakeholder',
    'blocker': 'Blocker',
    'introducer': 'Introducer'
  };
  return roleMap[role?.toLowerCase()] || 'Stakeholder';
}

function generateArchetype(member: any) {
  return {
    id: 'education-leader',
    name: 'Education Leader',
    role: member.role || 'Stakeholder',
    description: 'Leader focused on student success and institutional outcomes',
    characteristics: {
      motivations: ['Student success', 'Institutional excellence', 'Data-driven decisions'],
      concerns: ['Retention rates', 'Student outcomes', 'Resource allocation'],
      decisionMakingStyle: 'Data-driven with focus on student impact',
      communicationStyle: 'Collaborative, evidence-based, student-centric',
      keyNeeds: ['Student data', 'Retention metrics', 'Intervention strategies']
    }
  };
}

function generateStrategy(member: any) {
  return {
    situation: `${member.name} is responsible for ${member.title?.toLowerCase() || 'student success'} at WGU.`,
    complication: 'Struggling with student retention and engagement metrics.',
    futureState: 'A comprehensive retention solution that improves student outcomes and institutional performance.'
  };
}

export default function WGURetentionPage() {
  // Transform the data
  const { companyInfo, buyerGroup } = transformData(wguData);

  if (!buyerGroup || buyerGroup.totalMembers === 0) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">Loading WGU Intelligence...</h1>
          <p className="text-gray-600">Please wait while we load the buyer group data.</p>
          <p className="text-sm text-gray-500 mt-4">
            If this persists, run the pipeline: <code className="bg-gray-100 px-2 py-1 rounded">node scripts/_future_now/find-buyer-group/run-ei-wgu-retention.js</code>
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50" style={{ overflowY: 'auto', height: '100vh' }}>
      {/* Header */}
      <header className="border-b border-gray-100">
        <div className="max-w-6xl mx-auto px-6 py-4">
          <div className="flex justify-between items-center">
            <div className="flex items-center gap-4">
              <Link 
                href="/private/ei"
                className="text-sm text-gray-700 hover:text-gray-900 transition-colors"
              >
                ← Back to E&I Reports
              </Link>
              <h1 className="text-lg font-semibold text-gray-900">WGU Retention Buyer Group</h1>
            </div>
            
            <div className="flex items-center space-x-6">
              <Link 
                href="/" 
                className="text-sm text-gray-700 hover:text-gray-900 transition-colors"
              >
                Home
              </Link>
            </div>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-6xl mx-auto px-6 py-12">
        {/* Document Header */}
        <div className="border-b-2 border-black pb-8 mb-12">
          <h1 className="text-4xl font-bold text-black mb-4 leading-tight">
            WGU Buyer Group Intelligence Report
          </h1>
          <p className="text-xl text-muted mb-8">
            Strategic Analysis for E&I Cooperative Services: Student Retention Solution at Western Governors University
          </p>
          
          <div className="bg-panel-background p-6 rounded-lg border-l-4 border-gray-400">
            <div className="grid grid-cols-2 gap-6">
              <div>
                <p className="text-xs font-semibold text-muted uppercase tracking-wide">Prepared For</p>
                <p className="text-sm font-semibold text-black">E&I Cooperative Services</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-muted uppercase tracking-wide">Target Company</p>
                <p className="text-sm font-semibold text-black">Western Governors University (WGU)</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-muted uppercase tracking-wide">Product</p>
                <p className="text-sm font-semibold text-black">Student Retention Solution</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-muted uppercase tracking-wide">Deal Size</p>
                <p className="text-sm font-semibold text-black">$500K - $1.4M</p>
              </div>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-black mb-6">Executive Summary</h2>
          
          <p className="text-lg text-gray-700 mb-6 leading-relaxed">
            Western Governors University (WGU), a leading online competency-based university, presents a significant 
            opportunity for E&I Cooperative Services to provide a student retention solution. With WGU's strong emphasis 
            on student success and retention, a comprehensive retention platform priced between $500,000 and $1.4 million 
            aligns with their strategic priorities.
          </p>

          <div className="bg-panel-background border border-border p-6 rounded-lg mb-6">
            <h3 className="text-lg font-semibold text-black mb-3">Strategic Intelligence Advantage</h3>
            <p className="text-gray-700 mb-4">
              We've identified WGU's exact buyer group structure for student retention solutions, saving you months of 
              research. Our intelligence reveals the specific decision-makers, their influence patterns, pain points, 
              and the precise engagement sequence needed for successful deal closure.
            </p>
          </div>

          {/* Key Stats */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
            <div className="bg-panel-background p-4 rounded-lg text-center border border-border">
              <div className="text-3xl font-bold text-black">{buyerGroup.totalMembers}</div>
              <div className="text-sm text-muted">Buyer Group Size</div>
            </div>
            <div className="bg-panel-background p-4 rounded-lg text-center border border-border">
              <div className="text-3xl font-bold text-black">{buyerGroup.members.filter((m: BuyerGroupMember) => m.role === 'Decision Maker').length}</div>
              <div className="text-sm text-muted">Decision Makers</div>
            </div>
            <div className="bg-panel-background p-4 rounded-lg text-center border border-border">
              <div className="text-3xl font-bold text-black">{buyerGroup.members.filter((m: BuyerGroupMember) => m.role === 'Champion').length}</div>
              <div className="text-sm text-muted">Champions</div>
            </div>
            <div className="bg-panel-background p-4 rounded-lg text-center border border-border">
              <div className="text-3xl font-bold text-black">$500K-$1.4M</div>
              <div className="text-sm text-muted">Deal Value Range</div>
            </div>
          </div>
        </section>

        {/* Company Overview */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-black mb-6">WGU Company Overview</h2>
          
          <div className="bg-panel-background border border-border p-6 rounded-lg mb-8">
            <h3 className="text-xl font-semibold text-black mb-4">Company Profile</h3>
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <p className="text-sm text-gray-700 mb-2"><strong>Industry:</strong> {companyInfo.industry}</p>
                <p className="text-sm text-gray-700 mb-2"><strong>Company Size:</strong> {companyInfo.size}</p>
                <p className="text-sm text-gray-700 mb-2"><strong>Headquarters:</strong> {companyInfo.headquarters}</p>
                <p className="text-sm text-gray-700 mb-2"><strong>Website:</strong> <a href={companyInfo.website} className="text-blue-600 hover:underline">{companyInfo.website}</a></p>
              </div>
              <div>
                <p className="text-sm text-gray-700 mb-2"><strong>Focus:</strong> Online Competency-Based Education</p>
                <p className="text-sm text-gray-700 mb-2"><strong>Key Programs:</strong> Business, Education, Technology, Health</p>
                <p className="text-sm text-gray-700 mb-2"><strong>Retention Priority:</strong> High - Critical to institutional success</p>
              </div>
            </div>
          </div>
        </section>

        {/* Buyer Group Intelligence */}
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-black mb-6">WGU Buyer Group Intelligence</h2>
          
          <div className="bg-panel-background border border-border p-6 rounded-lg mb-8">
            <h3 className="text-xl font-semibold text-black mb-4">Strategic Context</h3>
            <p className="text-gray-700 mb-4">
              WGU operates as an online-only institution where student retention is critical to success. Their focus on 
              competency-based education requires sophisticated retention strategies to identify at-risk students early and 
              provide targeted interventions.
            </p>
            <p className="text-gray-700">
              <strong>Opportunity:</strong> WGU's emphasis on student success and retention, combined with their online 
              model, creates a compelling need for comprehensive retention solutions that can scale with their student population.
            </p>
          </div>

          {/* Buyer Group Members by Role */}
          <div className="space-y-8">
            {/* Decision Makers */}
            <div className="bg-white border border-gray-200 p-6 rounded-lg">
              <h4 className="text-lg font-semibold text-black mb-4">
                Decision Makers ({buyerGroup.members.filter((m: BuyerGroupMember) => m.role === 'Decision Maker').length})
              </h4>
              <div className="grid gap-6">
                {buyerGroup.members
                  .filter((member: BuyerGroupMember) => member.role === 'Decision Maker')
                  .map((member: BuyerGroupMember, index: number) => (
                    <div key={index} className="border border-gray-200 rounded-lg p-6">
                      <BuyerGroupMemberCard member={member as any} companySlug="wgu" />
                      {member.painPoints && member.painPoints.length > 0 && (
                        <div className="mt-4 pt-4 border-t border-gray-200">
                          <h5 className="text-sm font-semibold text-black mb-3">Pain Points</h5>
                          <div className="space-y-3">
                            {member.painPoints.map((pain: PainPoint, idx: number) => (
                              <div key={idx} className="bg-red-50 border-l-4 border-red-400 p-3 rounded">
                                <div className="flex items-start justify-between mb-1">
                                  <h6 className="text-sm font-semibold text-red-900">{pain.title}</h6>
                                  <span className={`text-xs px-2 py-1 rounded ${
                                    pain.urgency === 'high' ? 'bg-red-200 text-red-800' :
                                    pain.urgency === 'medium' ? 'bg-yellow-200 text-yellow-800' :
                                    'bg-gray-200 text-gray-800'
                                  }`}>
                                    {pain.urgency}
                                  </span>
                                </div>
                                <p className="text-sm text-gray-700 mb-1">{pain.description}</p>
                                <p className="text-xs text-gray-600"><strong>Impact:</strong> {pain.impact}</p>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
              </div>
            </div>

            {/* Champions */}
            <div className="bg-white border border-gray-200 p-6 rounded-lg">
              <h4 className="text-lg font-semibold text-black mb-4">
                Champions ({buyerGroup.members.filter((m: BuyerGroupMember) => m.role === 'Champion').length})
              </h4>
              <div className="grid gap-6">
                {buyerGroup.members
                  .filter((member: BuyerGroupMember) => member.role === 'Champion')
                  .map((member: BuyerGroupMember, index: number) => (
                    <div key={index} className="border border-gray-200 rounded-lg p-6">
                      <BuyerGroupMemberCard member={member as any} companySlug="wgu" />
                      {member.painPoints && member.painPoints.length > 0 && (
                        <div className="mt-4 pt-4 border-t border-gray-200">
                          <h5 className="text-sm font-semibold text-black mb-3">Pain Points</h5>
                          <div className="space-y-3">
                            {member.painPoints.map((pain: PainPoint, idx: number) => (
                              <div key={idx} className="bg-orange-50 border-l-4 border-orange-400 p-3 rounded">
                                <div className="flex items-start justify-between mb-1">
                                  <h6 className="text-sm font-semibold text-orange-900">{pain.title}</h6>
                                  <span className={`text-xs px-2 py-1 rounded ${
                                    pain.urgency === 'high' ? 'bg-red-200 text-red-800' :
                                    pain.urgency === 'medium' ? 'bg-yellow-200 text-yellow-800' :
                                    'bg-gray-200 text-gray-800'
                                  }`}>
                                    {pain.urgency}
                                  </span>
                                </div>
                                <p className="text-sm text-gray-700 mb-1">{pain.description}</p>
                                <p className="text-xs text-gray-600"><strong>Impact:</strong> {pain.impact}</p>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
              </div>
            </div>

            {/* Stakeholders */}
            <div className="bg-white border border-gray-200 p-6 rounded-lg">
              <h4 className="text-lg font-semibold text-black mb-4">
                Stakeholders ({buyerGroup.members.filter((m: BuyerGroupMember) => m.role === 'Stakeholder').length})
              </h4>
              <div className="grid gap-6">
                {buyerGroup.members
                  .filter((member: BuyerGroupMember) => member.role === 'Stakeholder')
                  .map((member: BuyerGroupMember, index: number) => (
                    <div key={index} className="border border-gray-200 rounded-lg p-6">
                      <BuyerGroupMemberCard member={member as any} companySlug="wgu" />
                      {member.painPoints && member.painPoints.length > 0 && (
                        <div className="mt-4 pt-4 border-t border-gray-200">
                          <h5 className="text-sm font-semibold text-black mb-3">Pain Points</h5>
                          <div className="space-y-3">
                            {member.painPoints.map((pain: PainPoint, idx: number) => (
                              <div key={idx} className="bg-blue-50 border-l-4 border-blue-400 p-3 rounded">
                                <div className="flex items-start justify-between mb-1">
                                  <h6 className="text-sm font-semibold text-blue-900">{pain.title}</h6>
                                  <span className={`text-xs px-2 py-1 rounded ${
                                    pain.urgency === 'high' ? 'bg-red-200 text-red-800' :
                                    pain.urgency === 'medium' ? 'bg-yellow-200 text-yellow-800' :
                                    'bg-gray-200 text-gray-800'
                                  }`}>
                                    {pain.urgency}
                                  </span>
                                </div>
                                <p className="text-sm text-gray-700 mb-1">{pain.description}</p>
                                <p className="text-xs text-gray-600"><strong>Impact:</strong> {pain.impact}</p>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}

